package org.spring.springboot.entity;


import java.util.Date;

public class TimeTaskSchedulCenterBean extends PageHelpBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_task_schedul_center.ID
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_task_schedul_center.SERVICE_NAME
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    private String serviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_task_schedul_center.SERVICE_VERSION
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    private String serviceVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_task_schedul_center.SERVICE_METHOD
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    private String serviceMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_task_schedul_center.SERVICE_CRON
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    private String serviceCron;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_task_schedul_center.CREATE_DATETIME
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_task_schedul_center.UPDATE_DATETIME
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    private Date updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time_task_schedul_center.SERVICE_ID
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    private String serviceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_task_schedul_center.ID
     *
     * @return the value of t_time_task_schedul_center.ID
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_task_schedul_center.ID
     *
     * @param id the value for t_time_task_schedul_center.ID
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_task_schedul_center.SERVICE_NAME
     *
     * @return the value of t_time_task_schedul_center.SERVICE_NAME
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_task_schedul_center.SERVICE_NAME
     *
     * @param serviceName the value for t_time_task_schedul_center.SERVICE_NAME
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_task_schedul_center.SERVICE_VERSION
     *
     * @return the value of t_time_task_schedul_center.SERVICE_VERSION
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    public String getServiceVersion() {
        return serviceVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_task_schedul_center.SERVICE_VERSION
     *
     * @param serviceVersion the value for t_time_task_schedul_center.SERVICE_VERSION
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    public void setServiceVersion(String serviceVersion) {
        this.serviceVersion = serviceVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_task_schedul_center.SERVICE_METHOD
     *
     * @return the value of t_time_task_schedul_center.SERVICE_METHOD
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    public String getServiceMethod() {
        return serviceMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_task_schedul_center.SERVICE_METHOD
     *
     * @param serviceMethod the value for t_time_task_schedul_center.SERVICE_METHOD
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    public void setServiceMethod(String serviceMethod) {
        this.serviceMethod = serviceMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_task_schedul_center.SERVICE_CRON
     *
     * @return the value of t_time_task_schedul_center.SERVICE_CRON
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    public String getServiceCron() {
        return serviceCron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_task_schedul_center.SERVICE_CRON
     *
     * @param serviceCron the value for t_time_task_schedul_center.SERVICE_CRON
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    public void setServiceCron(String serviceCron) {
        this.serviceCron = serviceCron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_task_schedul_center.CREATE_DATETIME
     *
     * @return the value of t_time_task_schedul_center.CREATE_DATETIME
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_task_schedul_center.CREATE_DATETIME
     *
     * @param createDatetime the value for t_time_task_schedul_center.CREATE_DATETIME
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_task_schedul_center.UPDATE_DATETIME
     *
     * @return the value of t_time_task_schedul_center.UPDATE_DATETIME
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_task_schedul_center.UPDATE_DATETIME
     *
     * @param updateDatetime the value for t_time_task_schedul_center.UPDATE_DATETIME
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time_task_schedul_center.SERVICE_ID
     *
     * @return the value of t_time_task_schedul_center.SERVICE_ID
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time_task_schedul_center.SERVICE_ID
     *
     * @param serviceId the value for t_time_task_schedul_center.SERVICE_ID
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    @Override
    public String toString() {
        return "TimeTaskSchedulCenterBean{" +
                "id='" + id + '\'' +
                ", serviceName='" + serviceName + '\'' +
                ", serviceVersion='" + serviceVersion + '\'' +
                ", serviceMethod='" + serviceMethod + '\'' +
                ", serviceCron='" + serviceCron + '\'' +
                ", createDatetime=" + createDatetime +
                ", updateDatetime=" + updateDatetime +
                ", serviceId='" + serviceId + '\'' +
                '}';
    }
}