package org.spring.springboot.dao;


import org.apache.ibatis.annotations.Param;
import org.spring.springboot.entity.TimeTaskSchedulCenterBean;
import org.spring.springboot.util.Page;
import org.springframework.stereotype.Repository;

import java.util.HashMap;

@Repository
public interface TimeTaskSchedulCenterDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_task_schedul_center
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_task_schedul_center
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    int insert(TimeTaskSchedulCenterBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_task_schedul_center
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    int insertSelective(TimeTaskSchedulCenterBean record);

    /**
     *改造查询方式使用map
     */

    Page<TimeTaskSchedulCenterBean> selectByPrimaryKey(HashMap<String,Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_task_schedul_center
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    int updateByPrimaryKeySelective(TimeTaskSchedulCenterBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time_task_schedul_center
     *
     * @mbg.generated Tue Aug 20 14:21:46 CST 2019
     */
    int updateByPrimaryKey(TimeTaskSchedulCenterBean record);

    TimeTaskSchedulCenterBean selectByPrimaryKeyTest(@Param("id") String id);
}